// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU3yBGi7ghAIygVC7-0gmPO9GJyHfplIE',
    appId: '1:632087938205:web:a5672686082cba19bfc074',
    messagingSenderId: '632087938205',
    projectId: 'flutter-crud-assignment-01',
    authDomain: 'flutter-crud-assignment-01.firebaseapp.com',
    databaseURL: 'https://flutter-crud-assignment-01-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-assignment-01.firebasestorage.app',
    measurementId: 'G-J5Y3PFVYK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDufbfY2qn5XNp0Iy-WZT4O3v4RN0P02nI',
    appId: '1:632087938205:android:c18b5b90a1fbeedabfc074',
    messagingSenderId: '632087938205',
    projectId: 'flutter-crud-assignment-01',
    databaseURL: 'https://flutter-crud-assignment-01-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-assignment-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb1ubh3hkXBRwl0YNRbj-UNpP7lUN0sdk',
    appId: '1:632087938205:ios:7fe73f9fbe74c00dbfc074',
    messagingSenderId: '632087938205',
    projectId: 'flutter-crud-assignment-01',
    databaseURL: 'https://flutter-crud-assignment-01-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-assignment-01.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb1ubh3hkXBRwl0YNRbj-UNpP7lUN0sdk',
    appId: '1:632087938205:ios:7fe73f9fbe74c00dbfc074',
    messagingSenderId: '632087938205',
    projectId: 'flutter-crud-assignment-01',
    databaseURL: 'https://flutter-crud-assignment-01-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-assignment-01.firebasestorage.app',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU3yBGi7ghAIygVC7-0gmPO9GJyHfplIE',
    appId: '1:632087938205:web:083e424b2980cab4bfc074',
    messagingSenderId: '632087938205',
    projectId: 'flutter-crud-assignment-01',
    authDomain: 'flutter-crud-assignment-01.firebaseapp.com',
    databaseURL: 'https://flutter-crud-assignment-01-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-crud-assignment-01.firebasestorage.app',
    measurementId: 'G-15ZWSPWWRF',
  );

}